src/zyx_rent/users/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'home', views.index, name='home'),

    # tenant
    url(r'^tenant/add/$', views.TenantEditView.as_view(), name='tenant_add'),
    url(r'^tenant/$', views.TenantListView.as_view(), name='tenant_list'),
    url(r'^tenant/(?P<pk>[\w-]+)/$', views.tenant, name='tenant'),
    url(r'^tenant/(?P<pk>[\w-]+)/edit/$', views.TenantEditView.as_view(), name='tenant_edit'),

    # property
    url(r'^property/add/$', views.PropertyEditView.as_view(), name='property_add'),
    url(r'^property/$', views.PropertyListView.as_view(), name='property_list'),
    url(r'^property/(?P<pk>[\w-]+)/$', views.property, name='property'),
    url(r'^property/(?P<pk>[\w-]+)/edit/$', views.PropertyEditView.as_view(), name='property_edit')

]

src/zyx_rent/zyx_rent/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('registration.backends.hmac.urls')),
]

src/zyx_rent/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.urlresolvers import reverse
from utilities.models import CreatedUpdatedModel


class Property(CreatedUpdatedModel):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=250)
    description = models.TextField()
    day_payment = models.IntegerField(
        default=1,
        validators=[MaxValueValidator(31), MinValueValidator(1)]
    )
    price = models.DecimalField(default=None, max_digits=6, decimal_places=2)
    owner = models.ForeignKey(User)
    tenant = models.ForeignKey('Tenant', null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('property', args=[self.id])

    def to_csv(self):
        return ','.join([
            self.name,
            self.address,
            self.description,
            str(self.day_payment),
            str(self.price)
        ])


class Tenant(CreatedUpdatedModel):
    name = models.CharField(max_length=100, default=None)
    email = models.EmailField()
    user = models.ForeignKey(User, blank=True)
    phone = models.CharField(max_length=100, blank=True)
    bank = models.CharField(max_length=100, blank=True)
    account = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name

    def to_csv(self):
        return ','.join([
            self.name,
            self.email,
            self.phone,
            self.bank,
            self.account
        ])

    def get_absolute_url(self):
        return reverse('tenant', args=[self.id])

src/zyx_rent/templates/properties/add.html
{% extends 'utilities/obj_edit.html' %}

{% load form_helpers %}


{% block form %}
    <div class="panel panel-default">
        <div class="panel-heading"><strong>Tenant</strong></div>
        <div class="panel-body">
            {% render_field form.name %}
            {% render_field form.address %}
            {% render_field form.description %}
            {% render_field form.day_payment %}
            {% render_field form.price %}
        </div>
    </div>
{% endblock %}

src/zyx_rent/templates/properties/list.html
{% extends '_base.html' %}
{% load helpers %}

{% block title %}Properties{% endblock %}

{% block content %}
<div class="pull-right">
    {% if perms.tenancy.add_property %}
		<a href="{% url 'property_add' %}" class="btn btn-primary">
			<span class="fa fa-plus" aria-hidden="true"></span>
			Add a property
		</a>
    {% endif %}
    {% include 'inc/export_button.html' with obj_type='properties' %}
</div>
<h1>Properties</h1>
<div class="row">
	<div class="col-md-9">
        {% include 'utilities/obj_table.html' %}
    </div>
    <div class="col-md-3">
		{% include 'inc/search_panel.html' %}
		{% include 'inc/filter_panel.html' %}
    </div>
</div>
{% endblock %}

src/zyx_rent/templates/properties/show.html
{% extends '_base.html' %}
{% load helpers %}

{% block title %}{{ property }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <ol class="breadcrumb">
            <li><a href="{% url 'property_list' %}">Properties</a></li>
            <li>{{ property }}</li>
        </ol>
    </div>
    <div class="col-md-3">
        <form action="{% url 'property_list' %}" method="get">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Name" />
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-search" aria-hidden="true"></span>
                    </button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="pull-right">
    {% if perms.tenancy.change_property %}
		<a href="{% url 'property_edit' pk=property.pk %}" class="btn btn-warning">
			<span class="fa fa-pencil" aria-hidden="true"></span>
			Edit this property
		</a>
    {% endif %}
</div>
<h1>{{ property }}</h1>
<div class="row">
	<div class="col-md-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Property</strong>
            </div>
            <table class="table table-hover panel-body">
                <tr>
                    <td>Name</td>
                    <td>{{ property.name }}</td>
                </tr>
                <tr>
                    <td>Address</td>
                    <td>{{ property.address }}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>{{ property.description }}</td>
                </tr>
                <tr>
                    <td>Price</td>
                    <td>{{ property.price }}</td>
                </tr>

                <tr>
                    <td>Day of Payment</td>
                    <td>{{ property.day_payment }}</td>
                </tr>


            </table>
        </div>
        {% with property.custom_fields as custom_fields %}
            {% include 'inc/custom_fields_panel.html' %}
        {% endwith %}
        {% include 'inc/created_updated.html' with obj=property %}
	</div>
</div>
{% endblock %}